version: 2.1

orbs:

jobs:
  build:
    macos:
      xcode: 14.3.1
    steps:
      - add_ssh_keys:
          fingerprints:
            - "85:de:23:a6:e2:6f:37:17:a9:62:bb:b3:61:b9:76:cb"
    
      - checkout
      
      - run:
          name: Setup ruby
          command: |
            echo 'ruby-3.2.2' > .ruby-version
            gem install bundler
            bundle install --jobs 4 --retry 3

      - run:
          name: Remove existing localization directory
          command: rm -rf station.localization
      
      - run:
          name: Clone localisation submodule
          command: git clone -b dev https://github.com/ruuvi/station.localization.git station.localization

      - run:
          name: CocoaPods Install
          command: pod install
      
      # - run:
      #     name: Install Provisioning Profiles
      #     command: |
      #       bundle exec fastlane match adhoc -a com.ruuvi.station,com.ruuvi.station.widgets,com.ruuvi.station.intents,com.ruuvi.station.pnservice --readonly
      #       bundle exec fastlane match development -a com.ruuvi.station,com.ruuvi.station.widgets,com.ruuvi.station.intents,com.ruuvi.station.pnservice --readonly
      #     environment:
      #       MATCH_PASSWORD: $MATCH_PASSWORD
      #       FASTLANE_PASSWORD: $FASTLANE_PASSWORD
      #       FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: $FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD
      #       KEYCHAIN_PASSWORD: $KEYCHAIN_PASSWORD
      #       LC_ALL: en_US.UTF-8
      #       LANG: en_US.UTF-8

      - run:
          name: Fastlane
          command: bundle exec fastlane --verbose upload_to_firebase build_number:407 scheme:station_dev
          environment:
            MATCH_PASSWORD: RuuviBear1
            FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD
            LC_ALL: en_US.UTF-8
            LANG: en_US.UTF-8

workflows:
  version: 2
  build:
    jobs:
      - build
