name: Distribute to Firebase

on:
  push:
    branches: [ "github-actions-firebase" ]

  workflow_dispatch:

jobs:
  deploy:
    name: Distributing to Firebase
    runs-on: macOS-12

    steps:      
    - name: Checkout
      uses: actions/checkout@v2

    - name: Select Xcode Version
      uses: sinoru/actions-setup-xcode@v2
      with:
        xcode-version: '13.4'
      
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
    
    - name: Setup ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'
        bundler-cache: true

    - name: CocoaPods Install
      run: pod install

    - name: Cocoapods Cache
      uses: actions/cache@v2
      with:
        path: Pods
        key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
        restore-keys: |
                ${{ runner.os }}-pods-

    - name: Run linters
      uses: wearerequired/lint-action@v2
      with:
        swiftlint: true

    - name: Build
      run: xcodebuild -workspace station.xcworkspace -scheme station -destination "generic/platform=iOS" -configuration Release build CODE_SIGNING_ALLOWED=NO
    
    - name: Deploy to Firebase via Fastlane 
      run: |
        bundle exec fastlane upload_to_firebase group:AlphaTesters scheme:station
      env:
        MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
        API_TOKEN: ${{ secrets.API_TOKEN }}
        FIREBASE_REFRESH_TOKEN: ${{ secrets.FIREBASE_REFRESH_TOKEN }}
        GOOGLE_APP_ID: ${{ secrets.GOOGLE_APP_ID }}
        PWD: ${{ secrets.PWD }}
    
          