name: Distribute to Firebase

on:
  push:
    branches: [ "github-actions-firebase" ]

  workflow_dispatch:

jobs:
  deploy:
    name: Distributing to Firebase
    runs-on: macOS-latest

    steps:      
    - name: Checkout
      uses: actions/checkout@v2

    - name: Select Xcode Version
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    
    - name: Try setting up SSH key
      uses: webfactory/ssh-agent@v0.5.4
      with:
          ssh-private-key: |
                ${{ secrets.KEYSTORE_PRIVATE_KEY }}
                ${{ secrets.CERT_PRIVATE_KEY }}
            
    - name: Try ssh connection
      run: |
          ssh -T git@github.com
            
    - name: Try cloning keystore
      run: |
        git clone git@github.com:ruuvi/com.ruuvi.station.ios.keystore.git
            
    - name: Try cloning certificates
      run: |
        git clone git@github.com:ruuvi/com.ruuvi.station.ios.certificates.git
      
    - name: Setup ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'
        bundler-cache: true

    - name: CocoaPods Install
      run: pod install

    - name: Cocoapods Cache
      uses: actions/cache@v2
      with:
        path: Pods
        key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
        restore-keys: |
                ${{ runner.os }}-pods-

    - name: Run linters
      uses: wearerequired/lint-action@v2
      with:
        swiftlint: true
    
    - name: Deploy to Firebase via Fastlane 
      run: |
        bundle exec fastlane upload_to_firebase build_number:304 scheme:station_dev
      env:
        MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
        API_TOKEN: ${{ secrets.API_TOKEN }}
        FIREBASE_REFRESH_TOKEN: ${{ secrets.FIREBASE_REFRESH_TOKEN }}
        GOOGLE_APP_ID: ${{ secrets.GOOGLE_APP_ID }}
        PWD: ${{ secrets.PWD }}
    
          
